### ISSUE TITLE
Najít cloudové řešení pro strojové učení

### ISSUE THREAD

**Issue by FandaCmuchar** [daviholy/projekt-parkoviste#16]
# Úvod

Bylo by vhodné a pohodlné použít cloudové úložiště s možností použití vzdáleného HW pro učení modelu.

## Příklad
[Azure](https://azure.microsoft.com/cs-cz/free/machine-learning/search/?&ef_id=Cj0KCQiAhf2MBhDNARIsAKXU5GQVTWk5DFLeSIKwJ9b5qcvxXUoZslqoA9EJwU2dhRoTVd565Mf-oCcaAuIeEALw_wcB:G:s&OCID=AID2200172_SEM_Cj0KCQiAhf2MBhDNARIsAKXU5GQVTWk5DFLeSIKwJ9b5qcvxXUoZslqoA9EJwU2dhRoTVd565Mf-oCcaAuIeEALw_wcB:G:s&gclid=Cj0KCQiAhf2MBhDNARIsAKXU5GQVTWk5DFLeSIKwJ9b5qcvxXUoZslqoA9EJwU2dhRoTVd565Mf-oCcaAuIeEALw_wcB)

**Comment by daviholy** [comment]
Nalezeno, bude se učit lokálně, přinejhorším se použije metaCentrum
