### ISSUE TITLE
Úprava CNN vstupu a výstupu

### ISSUE THREAD

**Issue by FandaCmuchar** [daviholy/projekt-parkoviste#21]
### Úvod

Pro zvýšení přesnosti modelu je nutné přidat rozpoznávání aut a prázdných míst zvlášť. Tímto způsobem budeme moct rozlišovat více stavů parkovacího místa a to: auto, prázdno, nějaký šum (např. člověk).

Bude potřeba upravit několik souborů a to NeuralNetwork, DatasetCreator, trainingModel a další...

### Příklad
Úprava modelu kde vstup a výstup bude tenzor s dimenzí nebo velikostí 2
car [1.0, 0.0], empty [0.0, 1.0], šum (člověk, ...) [0.0, 0.0]

**Comment by daviholy** [comment]
Hotovo. Možna bude později potřeba přidat další výstupní kategorii pro lidi, pokud si jí model bude plést s autama.
