### ISSUE TITLE
úprava ObjectPositionCoordinates

### ISSUE THREAD

**Issue by daviholy** [daviholy/projekt-parkoviste#5]
@Cemonix 
# důležité
- [x] přidat kontrolu bodů při kreslení obdélníků, pokud první je dolni pravý roh tak je prohodit

#
- [x] lépe okomentuj kód co je například legend(image_copy)? co je ar? type_p? atd...
- [x]  argument --out přejmenovat na json (už se vlastně nejedná jen na výstup, tak je matoucí to mít jako out)
- [x]  k argumentu --json pŕidat zkratku -j
- [x] k argumentu --json předělat default honotu na parkingPlaces.json
- [x] lépe popsat argument -view
- [x] #7
- [x] #8
- [x] možná zvětšit font? (u mě na 2k monitoru to je nečitelné), tady je asi možný problém že velikost je pevná, možnost dělat néjak dinamicky podle roylišení?
- [x]  u funkce rectangle_opencv zbytečně předáváš color, buď jí definuj přímo ve funkci
- [x] 85 -92 proč máš barvy přímo vepsané? použij color, který más definovaný, ale nevyužitý
- [x]  70-80 předélej na switch když už nechceś používat tu knihovnu, kterou jsem ti navrhoval  :D
- [x]  přidat dokumentaci hlavičky + funkcí jak je zvykem podle konvencí, viz např https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html
- [x]  na druhým řádku stačí napsat import cv2

**Comment by Cemonix** [comment]
6)
Použil jsem zip, protože potřebuju procházet 2 pole najednou (nebo sem mohl udělal pole polí, ale to by byly zase 2 for cykly nebo bych potřeboval counter)

7)
Zbytečná class a import knihovny navíc

11) Switch bohužel v pythonu neexistuje - je tu jen match case, ale ten je trochu odlišnej

**Comment by daviholy** [comment]
uprávy byly již implementovány
