### ISSUE TITLE
122 - 132, 85-92 místo stringu použij enumerátory

### ISSUE THREAD

**Issue by Cemonix** [daviholy/projekt-parkoviste#8]
Zbytečná classa a importovaná knihovna navíc, jen abych ušetřil pár uvozovek

**Comment by daviholy** [comment]
to není zbytečné, enum je ve standardní knihovně a importování je dost rzchlé, takže v tom problém není, enum ti nabízejí lepší možnosti debugování(nemůžež se upsat a mít někde například meyeru navíc) a navíc mají konstatní složitost, narozdíl od stringu, který jí má lineární
